https://www.youtube.com/watch?v=l_Wip8bEDFQ&list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH&index=37

# Most Frequent Value Imputation (Mode Imputation)

**Definition**

Most Frequent Value Imputation is a technique in which missing values are replaced with the **most frequently occurring value (mode)** of that column.

Although it can be applied to numerical data, it is mainly used for **categorical features**.

### When to Use
- When the feature is categorical.
- When the percentage of missing values is small.
- When the missing values are assumed to be random.

### Advantages
- Simple and easy to implement.
- Preserves the number of observations.

### Disadvantages
- Can change the distribution of the data.
- May introduce bias if many values are missing.

---

# Missing Category Imputation

Instead of replacing missing values with the mode, we can create a **new category** such as `"Missing"`.

This allows the model to learn that the value was originally missing instead of assuming it belongs to an existing category.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('train.csv',usecols=['GarageQual','FireplaceQu','SalePrice'])
df.head()

  FireplaceQu GarageQual  SalePrice
0         NaN         TA     208500
1          TA         TA     181500
2          TA         TA     223500
3          Gd         TA     140000
4          TA         TA     250000

# Check Missing Values

Calculate the percentage of missing values in each selected column.

In [5]:
df.isnull().mean()*100

FireplaceQu    47.260274
GarageQual      5.547945
SalePrice       0.000000
dtype: float64

In [6]:
df['GarageQual'].mode()

0    TA
Name: GarageQual, dtype: object

### Note:
Before imputation try visualization

# Save Original Distribution

Store the SalePrice distribution for houses having **GarageQual = TA** before performing imputation.

In [7]:
temp = df[df['GarageQual']=='TA']['SalePrice']

# Fill Missing Values with the Mode

Replace all missing values in **GarageQual** with the most frequent value (**TA**).

In [8]:
df['GarageQual'].fillna('TA', inplace=True)

/tmp/ipykernel_15245/1818999247.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GarageQual'].fillna('TA', inplace=True)

### Note:
Again check visuals

# Find the Mode of Fireplace Quality

Determine the most frequent category in the **FireplaceQu** column.

In [9]:
df['FireplaceQu'].mode()

0    Gd
Name: FireplaceQu, dtype: object

# Save Original Distribution

Store the SalePrice distribution for houses with **FireplaceQu = Gd** before imputation

In [10]:
temp = df[df['FireplaceQu']=='Gd']['SalePrice']

# Fill Missing Values with the Mode

Replace missing values in **FireplaceQu** with its most frequent category (**Gd**).

In [11]:
df['FireplaceQu'].fillna('Gd', inplace=True)

/tmp/ipykernel_15245/3912738894.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FireplaceQu'].fillna('Gd', inplace=True)

### Note:
Again check and compare visual before imputation

# Apply Most Frequent Value Imputation Using Scikit-learn

Split the dataset into training and testing sets before applying the imputer.

In [12]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    df.drop(columns=['SalePrice']),
    df['SalePrice'],
    test_size=0.2
)

# Create the Imputer

Create a `SimpleImputer` that replaces missing values with the most frequent value.

In [13]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='most_frequent')

# Fit and Transform the Data

Learn the most frequent value from the training data and use it to replace missing values in both the training and testing datasets.

In [15]:
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

# Display Learned Values

Display the most frequent value learned for each column during training.

In [16]:
imputer.statistics_

array(['Gd', 'TA'], dtype=object)